apiVersion: v1
kind: Service
metadata:
  name: extra-student-survey-service
spec:
  type: NodePort
  selector:
    app: extra-student-survey
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30036  # You can change this if you prefer
